word_hints = {
    "banana": "A long, curved yellow fruit.",
    "caramel": "A sweet sauce or candy made from sugar and milk.",
    "avocado": "A green fruit with a creamy texture and a large seed.",
    "coconut": "A tropical fruit with a hard shell and white edible flesh.",
    "pumpkin": "A large, round, orange fruit often carved during holidays.",
    "giraffe": "A tall animal with a very long neck.",
    "raccoon": "A nocturnal animal known for its masked face.",
    "parrot": "A colorful bird that can mimic sounds.",
    "balloon": "An inflatable object that can float in the air.",
    "butter": "A dairy product made by churning cream.",
    "address": "A location's description or a formal speech.",
    "success": "The achievement of a goal or desired result.",
    "letters": "Characters of the alphabet.",
    "pattern": "A repeated decorative design or sequence.",
    "tunnel": "An underground passage.",
    "process": "A series of actions taken to achieve a result.",
    "tornado": "A violently rotating column of air touching the ground.",
    "volcano": "A mountain that erupts with lava and ash.",
    "guitar": "A string instrument played by strumming or plucking.",
    "drummer": "A musician who plays the drums.",
    "bassoon": "A woodwind instrument with a long, curved shape.",
    "batman": "A dark-themed superhero fighting crime in Gotham City.",
    "joker": "A chaotic villain known for his unpredictable behavior.",
    "thanos": "A powerful villain from the Marvel universe.",
    "aladdin": "A fairy tale character who finds a magical lamp.",
    "tennis": "A sport played with rackets and a small ball.",
    "manager": "A person responsible for managing an organization or team.",
    "surgeon": "A doctor who performs operations.",
    "hammer": "A tool used for pounding nails.",
    "mirror": "A reflective surface that shows an image.",
    "bottles": "Containers used for holding liquids.",
    "glasses": "Eyewear used to correct or protect vision."
}
